In [1]:
import numpy as np

In [2]:
def pascal_tri(n):       # n = number of rows
    pascal = np.zeros((n, n), dtype=int)
    pascal[0, 0] = pascal[1, 0] = pascal[1, 1] = 1

    for row in range(2, n):
        for col in range(0, row+1):
            pascal[row, col] = pascal[row-1, col-1] + pascal[row-1, col]
    return pascal

In [3]:
def print_pascal(pascal):
    for row in range(0, n):
        for i in range(0, n-row):
            print(end = "  ")
        for x in pascal[row]:
            if x != 0: 
                print(x, end = "  ")
        print()

In [4]:
n = int(input("Insert a number of rows of Pascal's triangle:"))
tri1 = pascal_tri(n)
print(tri1)

Insert a number of rows of Pascal's triangle: 10


[[  1   0   0   0   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0   0   0   0]
 [  1   2   1   0   0   0   0   0   0   0]
 [  1   3   3   1   0   0   0   0   0   0]
 [  1   4   6   4   1   0   0   0   0   0]
 [  1   5  10  10   5   1   0   0   0   0]
 [  1   6  15  20  15   6   1   0   0   0]
 [  1   7  21  35  35  21   7   1   0   0]
 [  1   8  28  56  70  56  28   8   1   0]
 [  1   9  36  84 126 126  84  36   9   1]]


In [5]:
print_pascal(tri1)

                    1  
                  1  1  
                1  2  1  
              1  3  3  1  
            1  4  6  4  1  
          1  5  10  10  5  1  
        1  6  15  20  15  6  1  
      1  7  21  35  35  21  7  1  
    1  8  28  56  70  56  28  8  1  
  1  9  36  84  126  126  84  36  9  1  
